[Mosca] Remove travis and make changes to use github actions
dojot/iotagent-mosca pull request #123
Opened 2021-02-08 17:49 UTC by marianoleonardo

dojot/dojot#1913

2021-02-08 19:02 UTC, thiagodpf approved these changes

2021-02-09 20:27 UTC, mprevide requested changes
I left some comments

2021-02-09 20:27 UTC, mprevide commented on .github/workflows/main.yml
> +        npm test
You can to add license checks here.. It's just a suggestion

2021-02-09 20:27 UTC, mprevide commented on .github/workflows/main.yml
> +        name: ${{ steps.get_owner.outputs.owner }}/mosca
I think that name is wrong.. Check on Docker-compose or Ansible

2021-02-19 16:12 UTC, mprevide approved these changes

2021-02-22 11:22 UTC, thiagodpf approved these changes

2021-02-22 13:39 UTC, merged